/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "ms-rest-js";


/**
 * @interface
 * An interface representing V1Book.
 */
export interface V1Book {
  /**
   * @member {string} [name] Resource name of the book. It must have the format
   * of "shelves/*/books/*".
   * For example: "shelves/shelf1/books/book2".
   */
  name?: string;
}

/**
 * @interface
 * An interface representing V1ListBooksResponse.
 */
export interface V1ListBooksResponse {
  /**
   * @member {V1Book[]} [books] The field name should match the noun "books" in
   * the method name.  There
   * will be a maximum number of items returned based on the page_size field
   * in the request.
   */
  books?: V1Book[];
  /**
   * @member {string} [nextPageToken] Token to retrieve the next page of
   * results, or empty if there are no
   * more results in the list.
   */
  nextPageToken?: string;
}

/**
 * @interface
 * An interface representing GRPCSwagger練習ListBooksOptionalParams.
 * Optional Parameters.
 *
 * @extends RequestOptionsBase
 */
export interface GRPCSwagger練習ListBooksOptionalParams extends msRest.RequestOptionsBase {
  /**
   * @member {number} [pageSize] The maximum number of items to return.
   */
  pageSize?: number;
  /**
   * @member {string} [pageToken] The next_page_token value returned from a
   * previous List request, if any.
   */
  pageToken?: string;
}
