/*
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */


export const V1Book = {
  required: false,
  serializedName: 'v1Book',
  type: {
    name: 'Composite',
    className: 'V1Book',
    modelProperties: {
      name: {
        required: false,
        serializedName: 'name',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const V1ListBooksResponse = {
  required: false,
  serializedName: 'v1ListBooksResponse',
  type: {
    name: 'Composite',
    className: 'V1ListBooksResponse',
    modelProperties: {
      books: {
        required: false,
        serializedName: 'books',
        type: {
          name: 'Sequence',
          element: {
              required: false,
              serializedName: 'V1BookElementType',
              type: {
                name: 'Composite',
                className: 'V1Book'
              }
          }
        }
      },
      nextPageToken: {
        required: false,
        serializedName: 'next_page_token',
        type: {
          name: 'String'
        }
      }
    }
  }
};

export const GRPCSwagger練習ListBooksOptionalParams = {
  required: false,
  serializedName: 'ListBooksOptions',
  type: {
    name: 'Composite',
    className: 'GRPCSwagger練習ListBooksOptionalParams',
    modelProperties: {
      pageSize: {
        required: false,
        serializedName: 'page_size',
        type: {
          name: 'Number'
        }
      },
      pageToken: {
        required: false,
        serializedName: 'page_token',
        type: {
          name: 'String'
        }
      }
    }
  }
};
