// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shelves.proto

package shelves

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Book struct {
	// Resource name of the book. It must have the format of "shelves/*/books/*".
	// For example: "shelves/shelf1/books/book2".
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_shelves_d686884ddfcdc99f, []int{0}
}
func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (dst *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(dst, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetBookRequest struct {
	// Resource name of a book. For example: "shelves/shelf1/books/book2".
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookRequest) Reset()         { *m = GetBookRequest{} }
func (m *GetBookRequest) String() string { return proto.CompactTextString(m) }
func (*GetBookRequest) ProtoMessage()    {}
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_shelves_d686884ddfcdc99f, []int{1}
}
func (m *GetBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookRequest.Unmarshal(m, b)
}
func (m *GetBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookRequest.Marshal(b, m, deterministic)
}
func (dst *GetBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookRequest.Merge(dst, src)
}
func (m *GetBookRequest) XXX_Size() int {
	return xxx_messageInfo_GetBookRequest.Size(m)
}
func (m *GetBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookRequest proto.InternalMessageInfo

func (m *GetBookRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateBookRequest struct {
	// Resource name of the parent resource where to create the book.
	// For example: "shelves/shelf1".
	Parent string `protobuf:"bytes,1,opt,name=parent" json:"parent,omitempty"`
	// The Book resource to be created. Client must not set the `Book.name` field.
	Book                 *Book    `protobuf:"bytes,2,opt,name=book" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBookRequest) Reset()         { *m = CreateBookRequest{} }
func (m *CreateBookRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBookRequest) ProtoMessage()    {}
func (*CreateBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_shelves_d686884ddfcdc99f, []int{2}
}
func (m *CreateBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookRequest.Unmarshal(m, b)
}
func (m *CreateBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookRequest.Marshal(b, m, deterministic)
}
func (dst *CreateBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookRequest.Merge(dst, src)
}
func (m *CreateBookRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBookRequest.Size(m)
}
func (m *CreateBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookRequest proto.InternalMessageInfo

func (m *CreateBookRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CreateBookRequest) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

func init() {
	proto.RegisterType((*Book)(nil), "shelves.Book")
	proto.RegisterType((*GetBookRequest)(nil), "shelves.GetBookRequest")
	proto.RegisterType((*CreateBookRequest)(nil), "shelves.CreateBookRequest")
}

func init() { proto.RegisterFile("shelves.proto", fileDescriptor_shelves_d686884ddfcdc99f) }

var fileDescriptor_shelves_d686884ddfcdc99f = []byte{
	// 261 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0xce, 0x48, 0xcd,
	0x29, 0x4b, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0xa5, 0x64, 0xd2,
	0xf3, 0xf3, 0xd3, 0x73, 0x52, 0xf5, 0x13, 0x0b, 0x32, 0xf5, 0x13, 0xf3, 0xf2, 0xf2, 0x4b, 0x12,
	0x4b, 0x32, 0xf3, 0xf3, 0xa0, 0xca, 0x94, 0xa4, 0xb8, 0x58, 0x9c, 0xf2, 0xf3, 0xb3, 0x85, 0x84,
	0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x25,
	0x15, 0x2e, 0x3e, 0xf7, 0xd4, 0x12, 0x90, 0x74, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x09, 0x56,
	0x55, 0x7e, 0x5c, 0x82, 0xce, 0x45, 0xa9, 0x89, 0x25, 0xa9, 0xc8, 0x0a, 0xc5, 0xb8, 0xd8, 0x0a,
	0x12, 0x8b, 0x52, 0xf3, 0x4a, 0xa0, 0x4a, 0xa1, 0x3c, 0x21, 0x45, 0x2e, 0x96, 0xa4, 0xfc, 0xfc,
	0x6c, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x5e, 0x3d, 0x98, 0x9b, 0xc1, 0x7a, 0xc1, 0x52,
	0x46, 0xe7, 0x18, 0xb9, 0xf8, 0x7c, 0x32, 0x93, 0x8a, 0x12, 0x8b, 0x2a, 0x83, 0x53, 0x8b, 0xca,
	0x32, 0x93, 0x53, 0x85, 0xc2, 0xb9, 0xd8, 0xa1, 0x0e, 0x11, 0x12, 0x87, 0x6b, 0x41, 0x75, 0x9a,
	0x14, 0xaa, 0x59, 0x4a, 0x2a, 0x4d, 0x97, 0x9f, 0x4c, 0x66, 0x92, 0x13, 0x92, 0xd1, 0x2f, 0x33,
	0xd4, 0xaf, 0x06, 0x39, 0xd4, 0x16, 0x2a, 0xaf, 0xaf, 0xa5, 0x0f, 0xb2, 0xa7, 0x58, 0x5f, 0xab,
	0x56, 0x28, 0x99, 0x8b, 0x0b, 0xe1, 0x76, 0x21, 0x29, 0xb8, 0x11, 0x18, 0x1e, 0x42, 0x37, 0x5e,
	0x0b, 0x6c, 0xbc, 0x8a, 0x12, 0xc4, 0x78, 0x88, 0xe7, 0x10, 0x16, 0xd4, 0x42, 0x6c, 0xb0, 0x02,
	0x7b, 0x28, 0x89, 0x0d, 0x1c, 0xd2, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf4, 0x33, 0xf2,
	0x17, 0xa1, 0x01, 0x00, 0x00,
}
