// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shelves.proto

package co3k_shelves_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/empty"
import _ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ListBooksRequest struct {
	// The parent resource name, for example, "shelves/shelf1".
	Parent string `protobuf:"bytes,1,opt,name=parent" json:"parent,omitempty"`
	// The maximum number of items to return.
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	// The next_page_token value returned from a previous List request, if any.
	PageToken            string   `protobuf:"bytes,3,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBooksRequest) Reset()         { *m = ListBooksRequest{} }
func (m *ListBooksRequest) String() string { return proto.CompactTextString(m) }
func (*ListBooksRequest) ProtoMessage()    {}
func (*ListBooksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_shelves_060f8be3110dcfed, []int{0}
}
func (m *ListBooksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBooksRequest.Unmarshal(m, b)
}
func (m *ListBooksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBooksRequest.Marshal(b, m, deterministic)
}
func (dst *ListBooksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBooksRequest.Merge(dst, src)
}
func (m *ListBooksRequest) XXX_Size() int {
	return xxx_messageInfo_ListBooksRequest.Size(m)
}
func (m *ListBooksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBooksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBooksRequest proto.InternalMessageInfo

func (m *ListBooksRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ListBooksRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListBooksRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListBooksResponse struct {
	// The field name should match the noun "books" in the method name.  There
	// will be a maximum number of items returned based on the page_size field
	// in the request.
	Books []*Book `protobuf:"bytes,1,rep,name=books" json:"books,omitempty"`
	// Token to retrieve the next page of results, or empty if there are no
	// more results in the list.
	NextPageToken        string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBooksResponse) Reset()         { *m = ListBooksResponse{} }
func (m *ListBooksResponse) String() string { return proto.CompactTextString(m) }
func (*ListBooksResponse) ProtoMessage()    {}
func (*ListBooksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_shelves_060f8be3110dcfed, []int{1}
}
func (m *ListBooksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBooksResponse.Unmarshal(m, b)
}
func (m *ListBooksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBooksResponse.Marshal(b, m, deterministic)
}
func (dst *ListBooksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBooksResponse.Merge(dst, src)
}
func (m *ListBooksResponse) XXX_Size() int {
	return xxx_messageInfo_ListBooksResponse.Size(m)
}
func (m *ListBooksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBooksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBooksResponse proto.InternalMessageInfo

func (m *ListBooksResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

func (m *ListBooksResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type UpdateBookRequest struct {
	// The book resource which replaces the resource on the server.
	Book                 *Book    `protobuf:"bytes,1,opt,name=book" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBookRequest) Reset()         { *m = UpdateBookRequest{} }
func (m *UpdateBookRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBookRequest) ProtoMessage()    {}
func (*UpdateBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_shelves_060f8be3110dcfed, []int{2}
}
func (m *UpdateBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBookRequest.Unmarshal(m, b)
}
func (m *UpdateBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBookRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBookRequest.Merge(dst, src)
}
func (m *UpdateBookRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBookRequest.Size(m)
}
func (m *UpdateBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBookRequest proto.InternalMessageInfo

func (m *UpdateBookRequest) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type Book struct {
	// Resource name of the book. It must have the format of "shelves/*/books/*".
	// For example: "shelves/shelf1/books/book2".
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_shelves_060f8be3110dcfed, []int{3}
}
func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (dst *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(dst, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetBookRequest struct {
	// Resource name of a book. For example: "shelves/shelf1/books/book2".
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookRequest) Reset()         { *m = GetBookRequest{} }
func (m *GetBookRequest) String() string { return proto.CompactTextString(m) }
func (*GetBookRequest) ProtoMessage()    {}
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_shelves_060f8be3110dcfed, []int{4}
}
func (m *GetBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookRequest.Unmarshal(m, b)
}
func (m *GetBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookRequest.Marshal(b, m, deterministic)
}
func (dst *GetBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookRequest.Merge(dst, src)
}
func (m *GetBookRequest) XXX_Size() int {
	return xxx_messageInfo_GetBookRequest.Size(m)
}
func (m *GetBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookRequest proto.InternalMessageInfo

func (m *GetBookRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateBookRequest struct {
	// Resource name of the parent resource where to create the book.
	// For example: "shelves/shelf1".
	Parent string `protobuf:"bytes,1,opt,name=parent" json:"parent,omitempty"`
	// The Book resource to be created. Client must not set the `Book.name` field.
	Book                 *Book    `protobuf:"bytes,2,opt,name=book" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBookRequest) Reset()         { *m = CreateBookRequest{} }
func (m *CreateBookRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBookRequest) ProtoMessage()    {}
func (*CreateBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_shelves_060f8be3110dcfed, []int{5}
}
func (m *CreateBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookRequest.Unmarshal(m, b)
}
func (m *CreateBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookRequest.Marshal(b, m, deterministic)
}
func (dst *CreateBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookRequest.Merge(dst, src)
}
func (m *CreateBookRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBookRequest.Size(m)
}
func (m *CreateBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookRequest proto.InternalMessageInfo

func (m *CreateBookRequest) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *CreateBookRequest) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type DeleteBookRequest struct {
	// The resource name of the book to be deleted, for example:
	// "shelves/shelf1/books/book2"
	Name                 string   `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBookRequest) Reset()         { *m = DeleteBookRequest{} }
func (m *DeleteBookRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBookRequest) ProtoMessage()    {}
func (*DeleteBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_shelves_060f8be3110dcfed, []int{6}
}
func (m *DeleteBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBookRequest.Unmarshal(m, b)
}
func (m *DeleteBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBookRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBookRequest.Merge(dst, src)
}
func (m *DeleteBookRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBookRequest.Size(m)
}
func (m *DeleteBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBookRequest proto.InternalMessageInfo

func (m *DeleteBookRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*ListBooksRequest)(nil), "co3k.shelves.v1.ListBooksRequest")
	proto.RegisterType((*ListBooksResponse)(nil), "co3k.shelves.v1.ListBooksResponse")
	proto.RegisterType((*UpdateBookRequest)(nil), "co3k.shelves.v1.UpdateBookRequest")
	proto.RegisterType((*Book)(nil), "co3k.shelves.v1.Book")
	proto.RegisterType((*GetBookRequest)(nil), "co3k.shelves.v1.GetBookRequest")
	proto.RegisterType((*CreateBookRequest)(nil), "co3k.shelves.v1.CreateBookRequest")
	proto.RegisterType((*DeleteBookRequest)(nil), "co3k.shelves.v1.DeleteBookRequest")
}

func init() { proto.RegisterFile("shelves.proto", fileDescriptor_shelves_060f8be3110dcfed) }

var fileDescriptor_shelves_060f8be3110dcfed = []byte{
	// 618 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x94, 0xdf, 0x4e, 0x13, 0x4f,
	0x14, 0xc7, 0x7f, 0xdb, 0x16, 0x7e, 0x70, 0x94, 0x3f, 0x9d, 0x44, 0xd2, 0x2c, 0x20, 0xcb, 0x4a,
	0xb4, 0x54, 0xd9, 0x91, 0xe5, 0xae, 0x89, 0x24, 0x80, 0xc6, 0xc4, 0x90, 0x48, 0x0a, 0x72, 0xe1,
	0x0d, 0x99, 0xd6, 0xc3, 0x76, 0xa5, 0xdd, 0x19, 0x77, 0xa6, 0xb5, 0x60, 0xb8, 0xf1, 0x11, 0xf0,
	0x35, 0xbc, 0xf0, 0xc2, 0xc4, 0x4b, 0xdf, 0x41, 0x5f, 0xc1, 0x84, 0xd7, 0x30, 0x3b, 0xbb, 0xa5,
	0xd0, 0xed, 0xe2, 0x4d, 0xbb, 0x73, 0xe6, 0xcc, 0xf9, 0xcc, 0xf7, 0x3b, 0x27, 0x07, 0xa6, 0x64,
	0x13, 0x5b, 0x5d, 0x94, 0x8e, 0x08, 0xb9, 0xe2, 0x64, 0xa6, 0xc1, 0x37, 0x4e, 0x9c, 0x7e, 0xac,
	0xbb, 0x6e, 0x2e, 0x78, 0x9c, 0x7b, 0x2d, 0xa4, 0x4c, 0xf8, 0x94, 0x05, 0x01, 0x57, 0x4c, 0xf9,
	0x3c, 0x48, 0xd2, 0xcd, 0xf9, 0x64, 0x57, 0xaf, 0xea, 0x9d, 0x63, 0x8a, 0x6d, 0xa1, 0x4e, 0x93,
	0xcd, 0x27, 0xfa, 0xaf, 0xb1, 0xe6, 0x61, 0xb0, 0x26, 0x3f, 0x32, 0xcf, 0xc3, 0x90, 0x72, 0xa1,
	0x8f, 0xa7, 0x4b, 0xd9, 0xc7, 0x30, 0xbb, 0xeb, 0x4b, 0xb5, 0xcd, 0xf9, 0x89, 0xac, 0xe1, 0x87,
	0x0e, 0x4a, 0x45, 0xe6, 0x60, 0x5c, 0xb0, 0x10, 0x03, 0x55, 0x32, 0x2c, 0xa3, 0x3c, 0x59, 0x4b,
	0x56, 0x64, 0x1e, 0x26, 0x05, 0xf3, 0xf0, 0x48, 0xfa, 0x67, 0x58, 0xca, 0x59, 0x46, 0x79, 0xac,
	0x36, 0x11, 0x05, 0xf6, 0xfd, 0x33, 0x24, 0x8b, 0x00, 0x7a, 0x53, 0xf1, 0x13, 0x0c, 0x4a, 0x79,
	0x7d, 0x50, 0xa7, 0x1f, 0x44, 0x01, 0xbb, 0x09, 0xc5, 0x6b, 0x1c, 0x29, 0x78, 0x20, 0x91, 0x3c,
	0x86, 0xb1, 0x7a, 0x14, 0x28, 0x19, 0x56, 0xbe, 0x7c, 0xc7, 0xbd, 0xe7, 0x0c, 0xd9, 0xe0, 0x44,
	0xe9, 0xb5, 0x38, 0x87, 0x3c, 0x84, 0x99, 0x00, 0x7b, 0xea, 0xe8, 0x1a, 0x25, 0xa7, 0x29, 0x53,
	0x51, 0x78, 0xef, 0x8a, 0xb4, 0x09, 0xc5, 0x37, 0xe2, 0x1d, 0x53, 0xa8, 0x0f, 0x27, 0x92, 0x56,
	0xa1, 0x10, 0x55, 0xd1, 0x82, 0x32, 0x41, 0x3a, 0xc5, 0x36, 0xa1, 0x10, 0xad, 0x08, 0x81, 0x42,
	0xc0, 0xda, 0x98, 0x78, 0xa0, 0xbf, 0xed, 0x15, 0x98, 0x7e, 0x89, 0xea, 0x7a, 0xe1, 0x51, 0x59,
	0x87, 0x50, 0xdc, 0x09, 0x71, 0xe8, 0x06, 0x59, 0xa6, 0xf6, 0x6f, 0x96, 0xfb, 0xf7, 0xcd, 0x1e,
	0x41, 0xf1, 0x39, 0xb6, 0xf0, 0x66, 0xdd, 0x11, 0x17, 0x70, 0x7f, 0x15, 0x60, 0x7a, 0xd7, 0xaf,
	0x87, 0x2c, 0x3c, 0xdd, 0xc7, 0xb0, 0xeb, 0x37, 0x90, 0xf4, 0x60, 0xf2, 0xca, 0x7f, 0xb2, 0x9c,
	0xa2, 0x0c, 0xf7, 0x80, 0x69, 0xdf, 0x96, 0x12, 0x3f, 0x9f, 0xbd, 0xf2, 0xf9, 0xf7, 0x9f, 0x2f,
	0xb9, 0xfb, 0x64, 0x81, 0x76, 0xd7, 0xe9, 0xa7, 0x58, 0xcf, 0xb3, 0xe4, 0x04, 0xad, 0x9c, 0xd3,
	0xf8, 0xdd, 0x3c, 0xf8, 0x3f, 0xf1, 0x8c, 0x2c, 0xa5, 0x8a, 0xde, 0x74, 0xd3, 0x1c, 0x2d, 0x7f,
	0x08, 0x14, 0x49, 0x1c, 0x60, 0x62, 0x0a, 0xad, 0x9c, 0x13, 0x09, 0x30, 0xb0, 0x9d, 0xa4, 0x05,
	0xa4, 0xde, 0x24, 0x0b, 0x57, 0xd1, 0xb8, 0x15, 0xfb, 0x56, 0x5d, 0x55, 0xfd, 0x26, 0xa4, 0x07,
	0x30, 0xe8, 0xb6, 0x11, 0xd0, 0x54, 0x2b, 0x66, 0x41, 0xa9, 0x86, 0xae, 0xba, 0xcb, 0x1a, 0x1a,
	0xd5, 0x76, 0x32, 0x84, 0x26, 0xe4, 0x00, 0x60, 0xd0, 0x0d, 0x23, 0xc8, 0xa9, 0x56, 0x31, 0xe7,
	0x9c, 0x78, 0x6e, 0x38, 0xfd, 0xb9, 0xe1, 0xbc, 0x88, 0xe6, 0x46, 0xdf, 0xde, 0xca, 0xad, 0xf6,
	0x6e, 0x7f, 0x33, 0x2e, 0xb6, 0xbe, 0x1a, 0x64, 0x11, 0xe6, 0xbc, 0xda, 0xde, 0x8e, 0xb5, 0xb6,
	0x69, 0xed, 0xc7, 0xd3, 0xc5, 0xba, 0xfc, 0xf1, 0xfd, 0xf2, 0xe7, 0x85, 0x9b, 0x5f, 0x77, 0x9e,
	0x56, 0x8c, 0x9c, 0x3b, 0xcb, 0x84, 0x68, 0xf9, 0x0d, 0x3d, 0x66, 0xe8, 0x7b, 0xc9, 0x83, 0x6a,
	0x2a, 0xf2, 0xf6, 0x10, 0x0e, 0x60, 0xfc, 0xf5, 0x56, 0x47, 0x35, 0x5d, 0xf2, 0x6a, 0x22, 0x5f,
	0x2e, 0xb8, 0x0f, 0x9a, 0x4a, 0x09, 0x59, 0xa5, 0x14, 0x7b, 0xac, 0x2d, 0x5a, 0xe8, 0x34, 0x78,
	0x9b, 0x72, 0xd6, 0x51, 0x4d, 0x1a, 0xfd, 0xf0, 0xd0, 0x3f, 0xc3, 0xea, 0x52, 0x76, 0x92, 0x9e,
	0x08, 0xf5, 0xbb, 0x00, 0x57, 0x75, 0xff, 0xab, 0x8f, 0x6b, 0xa1, 0x1b, 0x7f, 0x03, 0x00, 0x00,
	0xff, 0xff, 0x49, 0x5e, 0xf3, 0xd1, 0x6e, 0x05, 0x00, 0x00,
}
