---
swagger: "2.0"
info:
  version: "version not set"
  title: "shelves.proto"
schemes:
- "http"
- "https"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /v1/{name}:
    get:
      tags:
      - "LibraryService"
      operationId: "GetBook"
      parameters:
      - name: "name"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "Name"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/shelvesBook"
  /v1/{parent}/books:
    post:
      tags:
      - "LibraryService"
      operationId: "CreateBook"
      parameters:
      - name: "parent"
        in: "path"
        required: true
        type: "string"
        x-exportParamName: "Parent"
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/shelvesBook"
        x-exportParamName: "Body"
      responses:
        200:
          description: ""
          schema:
            $ref: "#/definitions/shelvesBook"
definitions:
  shelvesBook:
    type: "object"
    properties:
      name:
        type: "string"
        description: "Resource name of the book. It must have the format of \"shelves/*/books/*\"\
          .\nFor example: \"shelves/shelf1/books/book2\"."
    example:
      name: "name"
