/*
 * mbox.proto
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: version not set
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type MboxMessage struct {

	From string `json:"from,omitempty"`

	To []string `json:"to,omitempty"`

	Subject string `json:"subject,omitempty"`

	Text string `json:"text,omitempty"`

	Html string `json:"html,omitempty"`
}
