/*
 * gRPC -> Swagger 練習
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type V1Book struct {

	// Resource name of the book. It must have the format of \"shelves/_*_/books/_*\". For example: \"shelves/shelf1/books/book2\".
	Name string `json:"name,omitempty"`
}
